### ISSUE TITLE
Add funding info in Dimensions

### ISSUE THREAD

**Issue by neesjanvaneck** [CWTSLeiden/cwts_covid#10]
@Giovanni1085 Would it be possible to add funding info in CWTS compatible Dimensions JSON files? Here is an example of how the data could be formatted: `"funding": [
{
"grid_id": "grid.48336.3a",
"grant_id": "100246152"
},
{
"grid_id": "grid.48336.3a",
"grant_id": null
}
]`

**Comment by Giovanni1085** [comment]
Ok, but the API does this differently now. A result is for example: `'supporting_grant_ids': ['grant.8360207']`, and then there needs to be another query to the API to get grant info. I am for now storing this as follows: `"funding": [ { "grid_id": None, "grant_id": "grant.8360207" } ]`. We could consolidate at some point and add the parallel queries needed to get all info down. How urgent this is @neesjanvaneck ?

**Comment by Giovanni1085** [comment]
Ok I have added this, putting in review

**Comment by neesjanvaneck** [comment]
Done
