### ISSUE TITLE
Query Dimensions also using publication IDs

### ISSUE THREAD

**Issue by Giovanni1085** [CWTSLeiden/cwts_covid#12]
Mainly to capture pre-print without DOI or PMID

**Comment by Giovanni1085** [comment]
Also need to add Dimensions ID as a valid identifier, to keep pre-print in the database

**Comment by Giovanni1085** [comment]
@neesjanvaneck, please review and close. Take note of minor changes in the SQL schema now (see the schema I uploaded in SURFdrive or here: https://github.com/CWTSLeiden/cwts_covid/tree/update/datasets_input/SQL_database_schema)

**Comment by neesjanvaneck** [comment]
Done
