### ISSUE TITLE
arXiv in CORD19

### ISSUE THREAD

**Issue by Giovanni1085** [CWTSLeiden/cwts_covid#18]
The latest release of CORD19 includes arXiv: https://www.semanticscholar.org/cord19/download

This, therefore, creates many duplicate records with Dimensions (which only considers 2020 and has a different query). Furthermore, some arXiv papers from CORD and all from dimensions do not have an `arxiv_id`. This will create duplicates. At the moment, CORD has 797 and Dimensions 598 articles from arXiv (1/5/2020).

I suggest we remove all arXiv from Dimensions and only consider those from CORD (because they also cover <2020). What do you think @neesjanvaneck @vtraag?

**Comment by vtraag** [comment]
So, from Dimensions it is clear that publications are from arXiv, but they are not assigned an arXiv identifier? How have you now identified whether they are duplicates, and could we not use that method then to deduplicate them similar to how we are dealing with DOIs and PMIDs now (using `groupby().first()`)?

**Comment by Giovanni1085** [comment]
> So, from Dimensions it is clear that publications are from arXiv, but they are not assigned an arXiv identifier? How have you now identified whether they are duplicates, and could we not use that method then to deduplicate them similar to how we are dealing with DOIs and PMIDs now (using `groupby().first()`)?

Nope, unfortunately. No arXiv paper from Dimensions has either DOI, PMID nor PMCID. 605 (out of 797) arXiv papers from CORD as well have no DOI, PMID nor PMCID. CORD provides with the arxiv_id, Dimensions provides with a dimensions_id for all of them. So, we don't have an identifier we can use for this, and we would need to go into metadata matching (something I'd rather avoid tbh).

**Comment by neesjanvaneck** [comment]
In the Dimensions web interface, the URL to the original full text is visible. In the case of arXiv publications, the arXiv identifier could perhaps be extracted from this URL. See for example: [https://app.dimensions.ai/details/publication/pub.1126058429](https://app.dimensions.ai/details/publication/pub.1126058429). It seems that this URL can be returned by the Dimensions API using the field `linkout`.

**Comment by Giovanni1085** [comment]
> In the Dimensions web interface, the URL to the original full text is visible. In the case of arXiv publications, the arXiv identifier could perhaps be extracted from this URL. See for example: https://app.dimensions.ai/details/publication/pub.1126058429. It seems that this URL can be returned by the Dimensions API using the field `linkout`.

Nice idea, I'll try this!

**Comment by Giovanni1085** [comment]
Done, @neesjanvaneck, please check

**Comment by Giovanni1085** [comment]
Closing as done.
