### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by vtraag** [CWTSLeiden/cwts_covid#2]
In the `README.md` it says 

> You will need to download these datasets and add them to a local folder in order to process them.

However, the datasets can now be found in the `datasets_input` directory. I assume this is not intended, as people should probably use the datasets from the original source?

There is also an empty `README.md` file in the `datasets_input` directory, you probably want to remove that as well?

**Comment by Giovanni1085** [comment]
See: 1c0bc0c405e38196e8bfdb501828e44ca35e9546

I deleted that secondary `README.md` and added a mention of the data files from the main `README.md`. We can keep them as examples and backup (not possible for CORD19, too large).
