### ISSUE TITLE
Dropping of duplicates

### ISSUE THREAD

**Issue by vtraag** [CWTSLeiden/cwts_covid#3]
At the moment duplicates are dropped based on whether they have an identical DOI or PM(C)ID. This may loose some information, which is a pity. Possibly, some rows may contain more information than others, so in principle, using all available information would be preferable.

Instead of doing
```
df_pub = df_pub[df_pub.doi!=""].drop_duplicates(['doi'])
```
and similar, you may prefer to do
```
df_pub = df_pub[df_pub.doi!=""].groupby('doi').first()
```
This groups by the DOI, and then use the first non-NA value for each column. Of course, information in multiple rows may not be fully consistent due to conflicting information. But in principle, this integrates the data better from all datasources.

**Comment by Giovanni1085** [comment]
Cool, I did not know. I will update with the next release.

**Comment by Giovanni1085** [comment]
Done, @vtraag please review and close (it is a minor thing, so I am not using a pull request)

**Comment by vtraag** [comment]
Looks good to me!

**Comment by vtraag** [comment]
It seems that there are 256 publications with duplicate DOIs in the resulting dataset, 3 publications with duplicate PMID and one with duplicate PMCID. There seems to be going something wrong, but I can't immediately spot what, perhaps you can take closer look @Giovanni1085 ?

**Comment by Giovanni1085** [comment]
@vtraag so I checked the `pub` table, and indeed there were some issues with capitalized DOIs and further string sanitization to be done to delete all possible duplicates (capitalized DOIs are considered as different from lowercased when doing a `drop_duplicates` call). Please do check on the 200410 version, as soon as ready, and let me know if there is still an issue (or close). Thanks!

**Comment by vtraag** [comment]
I believe this issue has been properly solved (at least in the 200701 version).
