### ISSUE TITLE
Add MeSH in Dimensions

### ISSUE THREAD

**Issue by Giovanni1085** [CWTSLeiden/cwts_covid#5]
From Ismael: enrich dimensions with PubMed, it would be helpful to have accurate health descriptors (MeSH).

**Comment by Giovanni1085** [comment]
@neesjanvaneck is this something we can easily integrate into the Dimensions schema by any chance?

**Comment by neesjanvaneck** [comment]
@Giovanni1085 Sure, could you ingest this in the JSON as a string array called `"mesh_headings"`? (Similar to the `"concepts"` string array that is already included.) For example, like this:
`"mesh_headings": [
"Brain Ischemia",
"Echocardiography, Transesophageal",
"Embolism",
"Female",
"Heart Diseases",
"Humans",
"Male"
]`

**Comment by Giovanni1085** [comment]
> @Giovanni1085 Sure, could you ingest this in the JSON as a string array called `"mesh_headings"`? (Similar to the `"concepts"` string array that is already included.) For example, like this:
> `"mesh_headings": [ "Brain Ischemia", "Echocardiography, Transesophageal", "Embolism", "Female", "Heart Diseases", "Humans", "Male" ]`

👍 Will do for next update.

**Comment by Giovanni1085** [comment]
Done and put for you to review, @neesjanvaneck

**Comment by neesjanvaneck** [comment]
Done
