### ISSUE TITLE
Add preprint info in Dimensions

### ISSUE THREAD

**Issue by neesjanvaneck** [CWTSLeiden/cwts_covid#9]
@Giovanni1085 Would it be possible to add the attribute `resulting_publication_doi` in CWTS compatible Dimensions JSON files? This attribute should contain for preprints the DOI of the resulting full publication.

**Comment by Giovanni1085** [comment]
Done and put for you to review, @neesjanvaneck

**Comment by neesjanvaneck** [comment]
Done
